# Generated by Django 3.1.1 on 2020-10-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('PassWord', models.CharField(max_length=20)),
                ('CPassWord', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
