# Generated by Django 3.1.1 on 2020-10-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0002_auto_20201003_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('passWord', models.CharField(max_length=20)),
            ],
        ),
    ]
