# Generated by Django 3.1.1 on 2020-10-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=100)),
            ],
        ),
    ]
